### PR TITLE
Resize text and icons

### PR DESCRIPTION
**Pull request by gamma032steam**
- Increase font size of the 'today' counter and note text
- Fix icon size & aspect ratio

**Web**
firefox_eMrEqj7odd

**Mobile**
firefox_ZPRWwhYbL2

### CODE REVIEW

**Comment by freddiewanah** [comment]
I don't have a strong intention to apply these changes. @PenguinPP @andrewzhang3 @BoxHezi @wooyunlong ?

**Comment by gamma032steam** [comment]
Can take out the font size change. It looks OK on mobile & laptop, but I have to squint a bit on my computer monitor.

Icon changes just bring them to the same aspect ratio as they appear on the map.

**Comment by andrewzhang3** [comment]
Screen Shot 2020-03-25 at 7 06 14 PM
Screen Shot 2020-03-25 at 7 05 32 PM
I think this change is a good QOL update. Right now the icons look a bit squashed. And yeah I think can keep the font size change as well.

**Comment by andrewzhang3** [comment]
Can you check that this update works well on other browsers at different screen sizes?@gamma032steam

**Comment by gamma032steam** [comment]
Chrome looks the same as Firefox.

**Mobile:**
chrome_MvAw4naetL


For context - here's how it looks for me?
firefox_rLlNVfXJao

**Comment by freddiewanah** [comment]
@andrewzhang3  approve?

**Pull request merged**
