### PR TITLE
add info page

### PR DESCRIPTION
**Pull request by andrewzhang3**
I've added the information page where if you add info into the info.json file, it will automatically render it into the information page. This however makes it harder to customise, but reduces code smell. Since the information page is static information, we could potentially make it all hardcoded in and therefore have more customisation.

### CODE REVIEW

**Comment by Jerenyaoyelu** [comment]
If you have not modified a file(new feat, fix or refactor), if all the changes are just indents because of some auto-align extension like prettier, you should avoid pushing such code. It will be very hard for a reviewer to review your code.

ONLY PUSH WHAT YOU HAVE CHANGED(FEAT, FIX, OR REFACTOR).

**Comment by andrewzhang3** [comment]
Hi Jerenyaoyelu, apologies for that. I've the changes I've made are adding the info.json file, and adding the Information function into App.js. It should be just above the App function. I've also installed react-uuid. 

I've added an import statement for info.json and uuid at the top, and added a <Grid> containing <Information> function inside of the App function aswell. No other changes anywhere else.

Apologies for the messy pull request, would it be better to close the pull request and remake it? Thanks

**Comment by Jerenyaoyelu** [comment]
Just my advice, I think you can roll back and commit to the same pr again. Let's make a reviewer's life easier. Cheers!

**Comment by andrewzhang3** [comment]
I've fixed the formatting problems. Hope this helps in reviewing the code! Sorry about all that haha, let me know if you need anything else. Thanks!

**Pull request merged**
