### PR TITLE
Choropleth map for vic & au bounds

### PR DESCRIPTION
**Pull request by morpheusp2p**
Add GeoBounds on map to show only AU. Default view is shown below
image

### CODE REVIEW

**Comment by freddiewanah** [comment]
Hi Saharsh, Can you redirect this PR to dev branch?

**Comment by morpheusp2p** [comment]
Redirected and resolved commits.

**Comment by morpheusp2p** [comment]
Done

**Comment by morpheusp2p** [comment]
Update map image showing VIC cities cases
image

**Pull request merged**
