### PR TITLE
adds accessible page

### PR DESCRIPTION
**Pull request by cagataygoncu**
Hi, 

This is a template page for the accessible version of the web site.

Cheers,
Chatai

### CODE REVIEW

**Comment by freddiewanah** [comment]
Hi Chatai,

looks like you've created all the accessibility files in a subfolder. Any other work needs to be done in the App.js to include it?

Also could you please redirect your pr to dev branch? 

thx 
Han

**Comment by cagataygoncu** [comment]
Hi Han,

Yes, they are all in one directory.

I am not sure regarding the App.js now. We will later probably need a link on the web page that will divert it to the accessible page after we finsalised the accessible page.

Cheers,
Chatai

**Comment by freddiewanah** [comment]
cool I can help with an extra page thing. 

For now, as you can see there're too many conflicts as we only need an extra folder. I guess I can create a separate branch and allow the PR. Then I can just checkout that folder to dev

**Comment by freddiewanah** [comment]
So I've created a new branch _sonification_  can you redirect it to there? Sorry for the inconvenience here (

**Comment by cagataygoncu** [comment]
Done!

**Comment by freddiewanah** [comment]
in dev and will push to prod tonight !

**Pull request closed without merging**
