### PR TITLE
Move GitHub link to icon button, add viewer icon to viewer stats

### PR DESCRIPTION
**Pull request by tuankhoin**
Just brushing up page end a bit.
image

### CODE REVIEW

**Comment by freddiewanah** [comment]
wondering how it looks on small screen like iphone se

**Comment by gamma032steam** [comment]
See [here ](https://superuser.com/questions/1214829/how-can-i-view-the-mobile-version-of-a-webpage-in-google-chrome-for-desktop)for how to test on mobile @tuankhoin. It might be better off in its own row under the 3 existing buttons.

Can we use the GitHub logo instead of a cog?

**Comment by tuankhoin** [comment]
Here's an image on mobile version @freddiewanah 
image
@gamma032steam I tried to find one in the bootstrap library icons, but they don't have logos. I'll look for another source in my free time.

**Comment by tuankhoin** [comment]
image
Fixed according to @gamma032steam 's recommendation.

**Pull request merged**
