### PR TITLE
Accessibility description generation for vision impaired users

### PR DESCRIPTION
**Pull request by ish-joshi**
I added a few messages for vision-impaired users, especially who are using screenreaders. 

First in the **Status** section where each cell "confirmed", "deaths" and "recovered" reads it as a group. 

Secondly made the table data rows act as a group and reads a description generated for each state.

### CODE REVIEW

**Comment by freddiewanah** [comment]
Wow really appreciate what you're doing here sir. 
Just is it possible that you can redirect your PR to the dev branch?

**Comment by freddiewanah** [comment]
@ish-joshi I'm sorry, but have you met any difficulties on changing it? I'm happy to merge it btw

**Comment by ish-joshi** [comment]
Hey @freddiewanah 

I was just having difficulty changing it on my phone haha. But if you're happy to merge it in that'd be great. However, it has conflicts with dev so it'd be nice to resolve them for other pr's that are pending. 

What do you suggest?

**Comment by freddiewanah** [comment]
I think it's normal since we have updated the branch frequently. Leave the confilcts to me. I can fix them before merge to dev.

**Comment by ish-joshi** [comment]
@freddiewanah feel free to merge it in. Let me know if you need any help

**Comment by freddiewanah** [comment]
Yeah, like I said can you redirect this pr to dev branch instead of prod?

**Comment by ish-joshi** [comment]
@freddiewanah done

**Pull request merged**
